[package]
name = "soc-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
colored = "2.1.0"
ctrlc = "3.4.5"
hex = "0.4.3"
notify = "5.0"
serde = "1.0.215"
serde_json = "1.0.133"
sha3 = "0.10.8"
tokio = { version = "1", features = ["full"] }
